[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }  # 'derive' 기능을 활성화
dotenv = "0.15.0"
